##
## Makefile for mysh in /home/fourri_l/Projects/repo-42sh
## 
## Made by Laurent Fourrier
## Login   <fourri_l@epitech.net>
## 
## Started on  Wed May 28 13:51:01 2014 Laurent Fourrier
## Last update Wed May 28 14:10:54 2014 Laurent Fourrier
##

## Makefile automatically generated by TPrCfg

CC	=	cc

RM	=	rm -rf

SRCDIR	=	src

LIBDIR	=	lib

INCDIR	=	include

CFLAGS	=	-Wall -pedantic	\
		-iquote$(INCDIR)	\
		-I$(LIBDIR)/tlist/include	\
		-I$(LIBDIR)/tio/include	\
		-I$(LIBDIR)/tutils/include	\
		-I$(LIBDIR)/tsys/include	\
		-iquote$(LIBDIR)/my/include	\
		-l/usr/lib	\

LDFLAGS	= \
		-ltlist -L$(LIBDIR)/tlist/	\
		-ltio -L$(LIBDIR)/tio/	\
		-ltutils -L$(LIBDIR)/tutils/	\
		-ltsys -L$(LIBDIR)/tsys/	\
		-lmy -L$(LIBDIR)/my/	\
		-lncurses	\

SRC	=	$(SRCDIR)/builtin/chdir.c	\
		$(SRCDIR)/builtin/my_strendcmp.c	\
		$(SRCDIR)/builtin/launch.c	\
		$(SRCDIR)/builtin/launch_redir_right.c	\
		$(SRCDIR)/builtin/launch_pipe.c	\
		$(SRCDIR)/builtin/exit.c	\
		$(SRCDIR)/builtin/process_cmdlist.c	\
		$(SRCDIR)/builtin/launcher/io.c	\
		$(SRCDIR)/builtin/launcher/redir.c	\
		$(SRCDIR)/builtin/launcher/pipe.c	\
		$(SRCDIR)/builtin/heredoc.c	\
		$(SRCDIR)/builtin/history.c	\
		$(SRCDIR)/builtin/wildcards.c	\
		$(SRCDIR)/builtin/alias/destroy.c	\
		$(SRCDIR)/builtin/alias/unalias.c	\
		$(SRCDIR)/builtin/alias/alias.c	\
		$(SRCDIR)/builtin/launch_redir_left.c	\
		$(SRCDIR)/builtin/launch_binary.c	\
		$(SRCDIR)/builtin/unsetenv.c	\
		$(SRCDIR)/builtin/launch_cmd.c	\
		$(SRCDIR)/builtin/setenv.c	\
		$(SRCDIR)/builtin/env.c	\
		$(SRCDIR)/builtin/divide_buffer_by_wcard.c	\
		$(SRCDIR)/builtin/chdir/chdir_buildbase.c	\
		$(SRCDIR)/builtin/chdir/chdir_newpath.c	\
		$(SRCDIR)/builtin/chdir/chdir_parent.c	\
		$(SRCDIR)/builtin/chdir/oldpwd.c	\
		$(SRCDIR)/builtin/chdir/chdir_enter.c	\
		$(SRCDIR)/builtin/stack_history.c	\
		$(SRCDIR)/script/launch.c	\
		$(SRCDIR)/script/exec_rtconf.c	\
		$(SRCDIR)/autocompletion/count_slash.c	\
		$(SRCDIR)/autocompletion/new_buffer.c	\
		$(SRCDIR)/autocompletion/lowerize.c	\
		$(SRCDIR)/autocompletion/get_home.c	\
		$(SRCDIR)/autocompletion/autocompletion.c	\
		$(SRCDIR)/autocompletion/divide_buffer.c	\
		$(SRCDIR)/autocompletion/str_to_wtab.c	\
		$(SRCDIR)/autocompletion/sort_word.c	\
		$(SRCDIR)/autocompletion/is_cmd.c	\
		$(SRCDIR)/autocompletion/show_xdir.c	\
		$(SRCDIR)/autocompletion/malloc_str.c	\
		$(SRCDIR)/autocompletion/file_type.c	\
		$(SRCDIR)/autocompletion/completion_xdir.c	\
		$(SRCDIR)/autocompletion/xfree.c	\
		$(SRCDIR)/autocompletion/show_files.c	\
		$(SRCDIR)/line_edit/set_termios.c	\
		$(SRCDIR)/line_edit/work_on_term.c	\
		$(SRCDIR)/line_edit/free_tab.c	\
		$(SRCDIR)/line_edit/clear_window.c	\
		$(SRCDIR)/line_edit/xmalloc.c	\
		$(SRCDIR)/line_edit/my_init.c	\
		$(SRCDIR)/line_edit/my_termios.c	\
		$(SRCDIR)/line_edit/start_sys.c	\
		$(SRCDIR)/line_edit/buffer_work.c	\
		$(SRCDIR)/line_edit/print_promp_buffer.c	\
		$(SRCDIR)/line_edit/take_new_pos.c	\
		$(SRCDIR)/line_edit/strcat_termios.c	\
		$(SRCDIR)/line_edit/swap_char.c	\
		$(SRCDIR)/line_edit/cp_paste.c	\
		$(SRCDIR)/line_edit/go_to_end.c	\
		$(SRCDIR)/line_edit/move_in_history.c	\
		$(SRCDIR)/line_edit/rewrite.c	\
		$(SRCDIR)/line_edit/key_funct.c	\
		$(SRCDIR)/line_edit/delete_until_end.c	\
		$(SRCDIR)/cmdparser/get_next_sym.c	\
		$(SRCDIR)/cmdparser/destroy_cmdlist.c	\
		$(SRCDIR)/cmdparser/parse_next.c	\
		$(SRCDIR)/cmdparser/get_lastcmd.c	\
		$(SRCDIR)/cmdparser/remove_nxtcmd.c	\
		$(SRCDIR)/cmdparser/parse.c	\
		$(SRCDIR)/cmdparser/get_paths.c	\
		$(SRCDIR)/cmdparser/transform.c	\
		$(SRCDIR)/cmdparser/get_sym.c	\
		$(SRCDIR)/system/wait_proc.c	\
		$(SRCDIR)/system/init.c	\
		$(SRCDIR)/system/init_shell.c	\
		$(SRCDIR)/system/destroy_system.c	\
		$(SRCDIR)/environment/print.c	\
		$(SRCDIR)/environment/check.c	\
		$(SRCDIR)/environment/get.c	\
		$(SRCDIR)/environment/set.c	\
		$(SRCDIR)/environment/create_path.c	\
		$(SRCDIR)/environment/parsevar.c	\
		$(SRCDIR)/environment/delete.c	\
		$(SRCDIR)/environment/cpy.c	\
		$(SRCDIR)/main.c	\
		$(SRCDIR)/arguments/restricted.c	\
		$(SRCDIR)/arguments/interactive.c	\
		$(SRCDIR)/arguments/login_shell.c	\
		$(SRCDIR)/arguments/command.c	\
		$(SRCDIR)/arguments/stdin.c	\
		$(SRCDIR)/arguments/parse_shell_args.c	\
		$(SRCDIR)/prompt/print.c	\
		$(SRCDIR)/prompt/update.c	\
		$(SRCDIR)/prompt/init.c	\
		$(SRCDIR)/prompt/loop.c	\
		$(SRCDIR)/prompt/getcmd.c	\

OBJ	=	$(SRC:.c=.o)

NAME	=	mysh

all: libs $(NAME)

$(NAME): $(OBJ)
	$(CC) -o $(NAME) $(OBJ) $(LDFLAGS)

libs:
	cd $(LIBDIR)/tlist && make
	cd $(LIBDIR)/tio && make
	cd $(LIBDIR)/tutils && make
	cd $(LIBDIR)/tsys && make
	cd $(LIBDIR)/my && make

clean:
	$(RM) $(OBJ)
	cd $(LIBDIR)/tlist && make clean
	cd $(LIBDIR)/tio && make clean
	cd $(LIBDIR)/tutils && make clean
	cd $(LIBDIR)/tsys && make clean
	cd $(LIBDIR)/my && make clean

fclean: clean
	$(RM) $(NAME)
	cd $(LIBDIR)/tlist && make fclean
	cd $(LIBDIR)/tio && make fclean
	cd $(LIBDIR)/tutils && make fclean
	cd $(LIBDIR)/tsys && make fclean
	cd $(LIBDIR)/my && make fclean

re: fclean all

.PHONY: all libs clean fclean re
